version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: globalize
    versions:
    - "< 6, > 5.0.1"
  - dependency-name: pg
    versions:
    - "< 2, >= 1.a"
  - dependency-name: recaptcha
    versions:
    - "< 4, >= 3.a"
  - dependency-name: recaptcha
    versions:
    - "< 5, >= 4.a"
  - dependency-name: turbolinks
    versions:
    - "< 6, >= 5.a"
  - dependency-name: faraday
    versions:
    - 1.3.0
    - 1.3.1
    - 1.4.0
  - dependency-name: omniauth-google-oauth2
    versions:
    - 0.8.1
  - dependency-name: excon
    versions:
    - 0.78.1
    - 0.79.0
    - 0.80.0
    - 0.80.1
  - dependency-name: grape
    versions:
    - 1.5.1
    - 1.5.2
  - dependency-name: grape-entity
    versions:
    - 0.8.2
  - dependency-name: mime-types-data
    versions:
    - 3.2020.1104
    - 3.2021.0212
  - dependency-name: grape-swagger
    versions:
    - 1.3.1
  - dependency-name: dry-logic
    versions:
    - 1.1.0
    - 1.1.1
  - dependency-name: chartkick
    versions:
    - 4.0.0
    - 4.0.1
    - 4.0.2
  - dependency-name: mini_mime
    versions:
    - 1.0.3
  - dependency-name: oauth2
    versions:
    - 1.4.5
    - 1.4.6
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: fog-aws
    versions:
    - 3.8.0
    - 3.9.0
  - dependency-name: pry
    versions:
    - 0.14.0
  - dependency-name: bulk_insert
    versions:
    - 1.8.2
  - dependency-name: timecop
    versions:
    - 0.9.3
  - dependency-name: brakeman
    versions:
    - 5.0.0
  - dependency-name: css_parser
    versions:
    - 1.8.0
  - dependency-name: dry-types
    versions:
    - 1.5.0
  - dependency-name: scout_apm
    versions:
    - 4.0.3
  - dependency-name: oauth
    versions:
    - 0.5.5
  - dependency-name: webdrivers
    versions:
    - 4.5.0
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: autoprefixer-rails
    versions:
    - 10.2.0.0
  - dependency-name: minitest
    versions:
    - 5.14.3
  - dependency-name: debug_inspector
    versions:
    - 1.0.0
  - dependency-name: dry-configurable
    versions:
    - 0.12.0
  - dependency-name: parser
    versions:
    - 3.0.0.0
  - dependency-name: unicorn
    versions:
    - 5.8.0
  - dependency-name: ffi
    versions:
    - 1.14.2
