inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*
    - lib/**/*
    - tmp/**/*
    - vendor/**/*

  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2
  DisabledByDefault: false

Rails:
  Enabled: true

# TODO: Resolve the following RuboCop violations

# Offense count: 1
# Configuration parameters: Include.
# Include: app/models/**/*.rb
Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 2
# Configuration parameters: Include.
# Include: app/**/*.rb, config/**/*.rb, db/**/*.rb, lib/**/*.rb
Rails/Output:
  Exclude:
    - 'config/unicorn.rb'

# Offense count: 1
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

# Offense count: 2
Lint/HandleExceptions:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'

Style/AndOr:
  Enabled: true

Metrics/LineLength:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
